import shelve, time, sys
from pathlib import Path
from shared.logger import Logger

class DataStoreReader:
    def __init__(self):
        self.base_dir = Path(__file__).parent.parent.parent.resolve()
        self.data_store_file = self.base_dir / "backend" / "xray_config" / "db" / "data_store.db"
        self.logger = Logger("DataStoreReader")
        self.required_keys = ["vless_uri", "qr_code_base64", "frontend_path"]
    
    def _open_data_store(self):
        return shelve.open(self.data_store_file)
    
    def get(self, key):
        with self._open_data_store() as db:
            return db.get(key, None)
    
    def wait_for_data_store(self, timeout: int = 120):
        self.logger.info("Waiting for data store to be generated by the backend...")
        
        start_time = time.time()
        while time.time() - start_time < timeout:
            if all(self.get(key) is not None for key in self.required_keys):
                self.logger.info("Data store is ready. Starting the frontend application...")
                return
            time.sleep(1)
        
        self.logger.error("Timeout waiting for data store to be ready. Frontend application cannot start.")
        sys.exit(1)