name: skyport staging CI

on: workflow_dispatch

jobs:
  build-skyport-staging:
    uses: ./.github/workflows/build-staging.yaml
    with:
      DOCKERHUB_USERNAME: xia1997x
      DOCKERHUB_REGISTRY: skyport
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  redeploy-skyport-staging:
    runs-on: ubuntu-latest
    steps:
      - name: post to webhook for redeployment
        run: curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK }}
    needs: [build-skyport-staging]

  check-skyport-server-connectivity:
    uses: ./.github/workflows/xray-connectivity-check.yaml
    secrets:
      XRAY_HOST: ${{ secrets.XRAY_HOST }}
      XRAY_PATH: ${{ secrets.XRAY_PATH }}
      XRAY_UUID: ${{ secrets.XRAY_UUID }}
      XRAY_ENCRYPTION_KEY: ${{ secrets.XRAY_ENCRYPTION_KEY }}
    needs: [redeploy-skyport-staging]

  post-checks:
    if: ${{ !cancelled() }} # Always run the job if not cancelled manually in the UI
    runs-on: ubuntu-latest
    steps:
      - name: Force fail after failed xray connectivity check
        run: |
          if [[ "${{ needs.check-xray-server-connectivity.result }}" == "failure" ]]; then
            echo "❌ xray-warp-ct staging CI workflow was not completed successfully!"
            exit 1
          else
            echo "✅ xray-warp-ct staging CI workflow completed successfully!"
          fi
    needs: [check-skyport-server-connectivity]
