name: xray connecitvity test

on:
  workflow_call:
    secrets:
      XRAY_HOST:
        required: True
      XRAY_PATH:
        required: True
      XRAY_UUID:
        required: True
      XRAY_ENCRYPTION_KEY:
        required: True

env:
  XRAY_HOST: ${{ secrets.XRAY_HOST }}
  XRAY_PATH: ${{ secrets.XRAY_PATH }}
  XRAY_UUID: ${{ secrets.XRAY_UUID }}
  XRAY_ENCRYPTION_KEY: ${{ secrets.XRAY_ENCRYPTION_KEY }}

jobs:
  xray-warp-ct-connecivity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start xray-warp-ct connectivity check
        run: |
          ./tests/client_server_test.sh
